# Generated by Django 5.1.3 on 2024-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_item_organization_items_tradeproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('membro', 'Membro'), ('capitão', 'Capitão')], max_length=50, null=True),
        ),
    ]
