# Generated by Django 5.1.3 on 2024-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('membro', 'Membro'), ('capitão', 'Capitão')], max_length=50, null=True),
        ),
    ]
